"""
This module contains default configuration of the admin plugin.

DO NOT EDIT THIS FILE, copy lines into `instance/config.py` to override.
"""
from whisper.core import app, require

require('core')

app.c.admin.auth.all = {}
# Example:
# app.c.admin.auth.all = {
#     'password': PasswordAuth(PasswordAuth.hash('123456')),
#     'cookie': CookieAuth('whisper-auth', 'This_1s-4_sUPer_secret_C00kie'),
#     'dummy': DummyAuth()
# }

app.c.admin.auth.policy = []
# Example:
# app.c.admin.auth.policy = [['password'], ['cookie', 'dummy']]

app.c.admin.page_size = 10
