"""
This module contains default configuration of the core 'plugin'.

The config object `c` is relatively imported, and options under the `core`
attribute is set to the default values. It's encouraged for plugin developer to
use this way for plugin options.

DO NOT EDIT THIS FILE, copy lines into `instance/config.py` to override.
"""
from whisper.core import app, require

require('core')

app.c.admin.auth.all = {}
# Example:
# app.c.admin.auth.all = {
#     'password': PasswordAuth(PasswordAuth.hash('123456')),
#     'cookie': CookieAuth('whisper-auth', 'This_1s-4_sUPer_secret_C00kie'),
#     'dummy': DummyAuth()
# }

app.c.admin.auth.policy = []
# Example:
# app.c.admin.auth.policy = [['password'], ['cookie', 'dummy']]
