"""
This module contains default configuration of the core 'plugin'.

The config object `c` is relatively imported, and options under the `core`
attribute is set to the default values. It's encouraged for plugin developer to
use this way for plugin options.

DO NOT EDIT THIS FILE, copy lines into `instance/config.py` to override.
"""
from . import app
from .provider import StubProvider as provider  # pylint: disable=unused-import

# the plugin used as main provider plugin (a.k.a. theme)
# this is the STUB provider, CHANGE IN PRODUCTION
app.c.core.main = 'core'
