"""
Defaults of the markdown provider.

DO NOT EDIT THIS FILE! copy lines into instance configuration to override.
"""
from whisper.core import app, require

from . import MarkdownProvider as provider  # pylint: disable=unused-import

require('core')

# the renderer to forward the result to
# can be override by post meta 'markdown:main'
app.c.markdown.main = 'main'

# passed to Python-Markdown
app.c.markdown.extensions = []
app.c.markdown.extension_configs = {}
app.c.markdown.kwargs = {}
