"""
This module contains default configuration of the markdown plugin.

DO NOT EDIT THIS FILE, copy lines into `instance/config.py` to override.
"""
from whisper.core import app, require
from . import MarkdownProvider as provider  # pylint: disable=unused-import

require('core')

# use specified provider to render file list
app.c.markdown.main = 'main'

# passed into Python-Markdown
app.c.markdown.extensions = []
app.c.markdown.extension_configs = {}
app.c.markdown.kwargs = {}
